credentials:
  usernames:
    admin:
      email: admin@admin.com
      name: Admin User
      password: hashed_password   # Needs to be replaced with a hashed password.
cookie:
  expiry_days: 30
  key: random_signature_key       # Must be a string.
  name: random_cookie_name
preauthorized:
  emails:
  - hreikin@gmail.com